# Generated by Django 4.0.1 on 2022-04-06 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farm_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nam', models.CharField(max_length=100)),
                ('cnum', models.CharField(max_length=100)),
                ('eml', models.CharField(max_length=100)),
                ('password', models.CharField(default='website', max_length=100)),
                ('anum', models.CharField(max_length=100)),
            ],
        ),
    ]
