# Generated by Django 4.1 on 2025-02-22 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("farmer", "0003_cart_shop_shopproduct_product_order_delivery_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shopproduct",
            name="description",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="shopproduct",
            name="image",
            field=models.ImageField(default=1, upload_to="products/"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="shopproduct",
            name="shop",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="farmer.shop"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="shopproduct",
            name="stock",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
