# Generated by Django 4.1 on 2025-02-22 10:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("farmer", "0004_shopproduct_description_shopproduct_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image2",
            field=models.ImageField(default=1, upload_to="products/"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="image3",
            field=models.ImageField(default=1, upload_to="products/"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="image4",
            field=models.ImageField(default=1, upload_to="products/"),
            preserve_default=False,
        ),
    ]
