# Generated by Django 4.1 on 2025-02-22 10:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("farmer", "0005_product_image2_product_image3_product_image4"),
    ]

    operations = [
        migrations.AddField(
            model_name="shopproduct",
            name="image2",
            field=models.ImageField(default=1, upload_to="products/"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="shopproduct",
            name="image3",
            field=models.ImageField(default=1, upload_to="products/"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="shopproduct",
            name="image4",
            field=models.ImageField(default=1, upload_to="products/"),
            preserve_default=False,
        ),
    ]
