# Generated by Django 4.1 on 2025-02-24 06:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("farmer", "0007_alter_cart_product_alter_cart_user_newcart"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="cart_items",
            field=models.ManyToManyField(to="farmer.newcart"),
        ),
    ]
