# Generated by Django 4.1 on 2025-02-27 09:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("farmer", "0010_product_cat_product_qty"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(upload_to="frproducts/"),
        ),
        migrations.AlterField(
            model_name="product",
            name="image2",
            field=models.ImageField(upload_to="frproducts/"),
        ),
        migrations.AlterField(
            model_name="product",
            name="image3",
            field=models.ImageField(upload_to="frproducts/"),
        ),
        migrations.AlterField(
            model_name="product",
            name="image4",
            field=models.ImageField(upload_to="frproducts/"),
        ),
    ]
