# Generated by Django 5.1.6 on 2025-03-04 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farmer", "0011_alter_product_image_alter_product_image2_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shop",
            name="role",
            field=models.CharField(default="farmer", max_length=100),
        ),
    ]
