# Generated by Django 5.1.6 on 2025-03-04 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farmer", "0013_alter_newcart_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="farmer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="farmer.shop"
            ),
        ),
    ]
