# Generated by Django 5.1.6 on 2025-03-05 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farmer", "0015_alter_cart_product_alter_cart_user_farmercart"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="farmer.shop"
            ),
        ),
    ]
